# [START runtime]
runtime: nodejs10
# [END runtime]

# [START handlers]
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  - url: /.*
    static_files: build/index.html
    upload: build/index.html